import { Book } from './app/shared/models/Book';
import { Manga } from './app/shared/models/Manga';
import { Music } from './app/shared/models/Music';
import { Novel } from './app/shared/models/Novel';
import { Tech } from './app/shared/models/Tech';

// export const sample_musics: Music[] = [
//     {
//       id:'1',
//       name: 'Pizza Pepperoni',

//       price: 10,
//       favorite: false,
//       origins: ['italy'],

//       imageUrl: 'assets/images/c3.jpg',
//       tags: ['FastFood', 'Pizza', 'Lunch'],
//     },
//   ]

export const sample_mangas: Manga[] = [
  {
    id: 'Manga1',
    title: 'Spy x Family',
    author: 'Tatsuya Endo',
    status: 'Ongoing',
    publish: 'June 25, 2019',
    language: 'English',
    imageUrl: 'assets/Manga/Spy x Family/Spy x Family.jpg',
    pdfUrl: 'assets/Manga/Spy x Family/Spy x Family.pdf',
    origin: 'Japan',
  },
  {
    id: 'Manga2',
    title: 'Your Name',
    author: 'Makoto Shinkai',
    status: 'Released',
    publish: 'August 26, 2016',
    language: 'English',
    imageUrl: 'assets/Manga/Your Name/Your Name.jpg',
    pdfUrl: 'assets/Manga/Your Name/Your Name.pdf',
    origin: 'Japan',
  },
  {
    id: 'Manga3',
    title: 'Death Note Special',
    author: 'Tsugumi Ohba',
    status: 'Released',
    publish: 'February 3rd, 2020',
    language: 'English',
    imageUrl: 'assets/Manga/Death Note/Death Note Special.png',
    pdfUrl: 'assets/Manga/Death Note/Death Note Special.pdf',
    origin: 'Japan',
  },
  {
    id: 'Manga4',
    title: 'One Piece',
    author: 'Eiichiro Oda',
    status: 'Ongoing',
    publish: 'July 22, 1997',
    language: 'English',
    imageUrl: 'assets/Manga/One Piece/One Piece.png',
    pdfUrl: 'assets/Manga/One Piece/One Piece.pdf',
    origin: 'Japan',
  },
  {
    id: 'Manga5',
    title: 'Blue Lock',
    author: 'Muneyuki Kaneshiro',
    status: 'Released',
    publish: 'March 25, 2023',
    language: 'English',
    imageUrl: 'assets/Manga/Blue Lock/Blue Lock.png',
    pdfUrl: 'assets/Manga/Blue Lock/Blue Lock ch1.pdf',
    origin: 'Japan',
  },
  {
    id: 'Manga6',
    title: 'I Got a Cheat Skill',
    author: 'Miku',
    status: 'Released',
    publish: 'September 10, 2010',
    language: 'English',
    imageUrl: 'assets/Manga/I Got a Cheat Skill/I Got a Cheat Skill.png',
    pdfUrl: 'assets/Manga/I Got a Cheat Skill/I Got a Cheat Skill.pdf',
    origin: 'Japan',
  },
  {
    id: 'Manga7',
    title: 'Attack on Titan',
    author: 'Hajime Isayama',
    status: 'Released',
    publish: 'September 9, 2009',
    language: 'English',
    imageUrl: 'assets/Manga/Attack on Titan/Attack on Titan.png',
    pdfUrl: 'assets/Manga/Attack on Titan/Attack on Titan.pdf',
    origin: 'Japan',
  },
  {
    id: 'Manga8',
    title: 'Jujutsu Kaisen',
    author: 'Akutami Gege',
    status: 'Ongoing',
    publish: 'March 5, 2018',
    language: 'English',
    imageUrl: 'assets/Manga/Jujutsu Kaisen/Jujutsu Kaisen.png',
    pdfUrl: 'assets/Manga/Jujutsu Kaisen/Jujutsu Kaisen.pdf',
    origin: 'Japan',
  },
  {
    id: 'Manga9',
    title: 'Erased',
    author: 'Kei Sanbe',
    status: 'Released',
    publish: 'Feb 21, 2017',
    language: 'English',
    imageUrl: 'assets/Manga/Erased/Erased.jpg',
    pdfUrl: 'assets/Manga/Erased/Erased.pdf',
    origin: 'Japan',
  },
];
export const sample_musics: Music[] = [
  {
    id: 'Music1',
    title: 'Suzume',
    author: 'Tatsuya Endo',
    publish: 'June  25, 2019',
    language: 'English',
    origin: 'Japan',
    imageUrl: 'assets/Manga/Spy x Family/Spy x Family.jpg',
    pdfUrl: 'assets/Manga/Spy x Family/Spy x Family.pdf',
  },
  {
    id: 'Music2',
    title: 'Your Name',
    author: 'Makoto Shinkai',
    publish: 'August 26, 2016',
    language: 'English',
    origin: 'Japan',
    imageUrl: 'assets/Manga/Your Name/Your Name.jpg',
    pdfUrl: 'assets/Manga/Your Name/Your Name.pdf',
  },
  {
    id: '3',
    title: 'Hamburger',
    author: 'Makoto Shinkai',
    publish: 'Null',
    language: 'English',
    origin: 'Japan',
    imageUrl: 'assets/images/c3.jpg',
    pdfUrl: 'assets/images/c3.jpg',
  },
  {
    id: '4',
    title: 'Fried Potatoes',
    author: 'Makoto Shinkai',
    publish: 'null',
    language: 'English',
    origin: 'Japan',
    imageUrl: 'assets/images/c3.jpg',
    pdfUrl: 'assets/images/c3.jpg',
  },
  {
    id: '5',
    title: 'Chicken Soup',
    author: 'Makoto Shinkai',
    publish: 'null',
    language: 'English',
    origin: 'Japan',
    imageUrl: 'assets/images/c3.jpg',
    pdfUrl: 'assets/images/c3.jpg',
  },
  {
    id: '6',
    title: 'Vegetables Pizza',
    author: 'Makoto Shinkai',
    publish: 'null',
    language: 'English',
    origin: 'Japan',
    imageUrl: 'assets/images/c3.jpg',
    pdfUrl: 'assets/images/c3.jpg',
  },
];
export const sample_techs: Tech[] = [
  {
    id: 'Tech1',
    title: 'Probability & Statistics for Scientists',
    author: 'Walpole, Myers, Myers, Ye',
    publish: 'Pearson',
    format: '812 pages',
    subject: 'Mathematics',
    imageUrl: 'assets/Other Books/Probability & Statistics for Scientists/Probability & Statistics for Scientists.png',
    pdfUrl: 'assets/Other Books/Probability & Statistics for Scientists/Text Book of Probability and Statistics.pdf',
  },
  {
    id: 'Tech2',
    title: 'Discrete Mathematics Applications',
    author: 'Kenneth H. Rosen',
    publish: 'McGraw Hills',
    format: '1071 pages',
    subject: 'Mathematics',
    imageUrl: 'assets/Other Books/Discrete Mathematics Applications/Discrete Mathematics Applications.png',
    pdfUrl: 'assets/Other Books/Discrete Mathematics Applications/Discrete Mathematics Applications.pdf',
  },
  {
    id: 'Tech3',
    title: 'WorkBook of Ananlytical Skills',
    author: 'Hanya Yanagihara',
    publish: 'D.A.S.C. L.P.U.',
    format: '116 pages',
    subject: 'Ananlytical Skills',
    imageUrl: 'assets/Other Books/WorkBook of Ananlytical Skills/WorkBook of Ananlytical Skills.png',
    pdfUrl: 'assets/Other Books/WorkBook of Ananlytical Skills/Workbook-PEA305.pdf',
  },
  {
    id: 'Tech4',
    title: 'Concepts And Applications Of UNIX',
    author: 'Sumitabha Das',
    publish: 'The McGraw Hills',
    format: '131 pages',
    subject: 'UNIX',
    imageUrl: 'assets/Other Books/Concepts And Applications Of UNIX.pdf/Concepts And Applications Of UNIX.pdf.png',
    pdfUrl: 'assets/Other Books/Concepts And Applications Of UNIX.pdf/Concepts And Applications Of UNIX.pdf',
  },
  {
    id: 'Tech5',
    title: 'Beginning Linux Programming',
    author: 'Matthew, Stones',
    publish: 'Wiley Publishing',
    format: '819 pages',
    subject: 'Linux Programming',
    imageUrl: 'assets/Other Books/Beginning Linux Programming/Beginning Linux Programming.png',
    pdfUrl: 'assets/Other Books/Beginning Linux Programming/Beginning Linux Programming, 4 Ed.pdf',
  },
  {
    id: 'Tech6',
    title: 'Let Us C by Yashwant Kanetkar',
    author: 'Yashwant Kanetkar',
    publish: 'BPB Publications',
    format: '636 pages',
    subject: 'C Programming',
    imageUrl: 'assets/Other Books/Let Us C/Let Us C.png',
    pdfUrl: 'assets/Other Books/Let Us C/let-us-c-14.pdf',
  },
  {
    id: 'Tech7',
    title: 'The C Programming Language',
    author: 'Kernighan, Ritche',
    publish: 'Hall Software',
    format: '238 pages',
    subject: 'C Programming',
    imageUrl: 'assets/Other Books/The C Programming Language/The C Programming Language.png',
    pdfUrl: 'assets/Other Books/The C Programming Language/C Language.pdf',
  },
  {
    id: 'Tech8',
    title: 'The C++ Programming Language',
    author: 'Bjarne Stroustrup',
    publish: 'Pearson Education',
    format: '1366 pages',
    subject: 'C++ Programming',
    imageUrl: 'assets/Other Books/C++ by Bjarne Stroustrup/The_C _Programming_Language_4th_Edition_Bjarne_Stroustrup.pdf.png',
    pdfUrl: 'assets/Other Books/C++ by Bjarne Stroustrup/The_C _Programming_Language_4th_Edition_Bjarne_Stroustrup.pdf',
  },
  {
    id: 'Tech9',
    title: 'Java',
    author: 'Edward D. Alphons',
    publish: 'Edward D. Alphons',
    format: '42 pages',
    subject: 'Java',
    imageUrl: 'assets/Other Books/Java  Edward D. Alphons/Java  Edward D. Alphons.png',
    pdfUrl: 'assets/Other Books/Java  Edward D. Alphons/Java  Edward D. Alphons.pdf',
  },
  {
    id: 'Tech10',
    title: 'HTML Cheat Sheet',
    author: 'Free Code Camp',
    publish: 'Free Code Camp',
    format: '15 pages',
    subject: 'HTML Cheat Sheet',
    imageUrl: 'assets/Other Books/HTML Cheat Sheet/HTML Cheat Sheet.png',
    pdfUrl: 'assets/Other Books/HTML Cheat Sheet/Html Cheatsheet.pdf',
  },
  {
    id: 'Tech11',
    title: 'CSS Cheat Sheet',
    author: 'Free Code Camp',
    publish: 'Free Code Camp',
    format: '23 pages',
    subject: 'CSS Cheat Sheet',
    imageUrl: 'assets/Other Books/CSS Cheat Sheet/CSS Cheat Sheet.png',
    pdfUrl: 'assets/Other Books/CSS Cheat Sheet/CSS Cheatsheet.pdf',
  },
  {
    id: 'Tech12',
    title: 'JS Cheat Sheet',
    author: 'Free Code Camp',
    publish: 'Free Code Camp',
    format: '22 pages',
    subject: 'JS Cheat Sheet',
    imageUrl: 'assets/Other Books/JS Cheat Sheet/Javascript Cheat Sheet.png',
    pdfUrl: 'assets/Other Books/JS Cheat Sheet/Javascript Cheat Sheet.pdf',
  },
  {
    id: 'Tech13',
    title: 'Data Communications & Networking',
    author: 'Behrouz A. Forouzan',
    publish: 'McGraw Hills',
    format: '1171 pages',
    subject: 'Computer Networking',
    imageUrl: 'assets/Other Books/Data Communications and Networking/Data Communications and Networking.png',
    pdfUrl: 'assets/Other Books/Data Communications and Networking/Data Communications and Networking.pdf',
  },
  {
    id: 'Tech14',
    title: 'Computer Organisation And Design',
    author: 'P. Pal Chaudhuri',
    publish: 'PHI Learning',
    format: '920 pages',
    subject: 'Computer Organisation',
    imageUrl: 'assets/Other Books/Computer Organisation And Design/Computer Organisation And Design.png',
    pdfUrl: 'assets/Other Books/Computer Organisation And Design/Computer Organisation And Design_by_p_pal_chaudhuri.pdf',
  },
  {
    id: 'Tech15',
    title: 'Computer System Architecture',
    author: 'Morris Mano',
    publish: 'Prentice Hall',
    format: '524 pages',
    subject: 'Computer Architecture',
    imageUrl: 'assets/Other Books/Computer System Architecture/Computer System Architecture.png',
    pdfUrl: 'assets/Other Books/Computer System Architecture/Computer System Architecture.pdf',
  },
  {
    id: 'Tech16',
    title: 'Machine Learning with Python',
    author: 'Ajigt Singh',
    publish: 'Ajit Singh',
    format: '137 pages',
    subject: 'Machine Learning',
    imageUrl: 'assets/Other Books/Machine Learning With Python/Machine Learning With Python.png',
    pdfUrl: 'assets/Other Books/Machine Learning With Python/Machine Learning With Python.pdf',
  },
  {
    id: 'Tech17',
    title: 'Engineering Physics',
    author: 'H.K.Malik, A.K.Singh',
    publish: 'McGraw Hills',
    format: '840 pages',
    subject: 'Physics',
    imageUrl: 'assets/Other Books/Enginnering Physics/Engineering Physics.jpg',
    pdfUrl: 'assets/Other Books/Enginnering Physics/Engineering Physics.pdf',
  },
];
export const sample_novel: Novel[] = [
  {
    id: 'Novel1',
    title: "Gulliver's Travels",
    author: 'Jonathan Swift',
    publish: '1726',
    format: '383 pages',
    language: 'English',
    imageUrl: "assets/Novels/Gulliver's Travels/Gullivers_Travels.jpeg",
    pdfUrl: "assets/Novels/Gulliver's Travels/Gullivers Travels.pdf",
  },
  {
    id: 'novel2',
    title: 'A Little Life',
    author: 'Hanya Yanagihara',
    publish: '10 Mar, 2015',
    format: '720 pages',
    language: 'English',
    imageUrl: 'assets/Novels/A Little Life/A_Little_Life.jpeg',
    pdfUrl: 'assets/Novels/A Little Life/A Little Life.pdf',
  },
  {
    id: 'Novel3',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    publish: '1 Jan, 1818',
    format: '276 pages',
    language: 'English',
    imageUrl: 'assets/Novels/Frankenstein/Frankenstein.png',
    pdfUrl: 'assets/Novels/Frankenstein/Frankenstein.pdf',
  },
  {
    id: 'Novel4',
    title: 'Three Men In A Boat',
    author: 'Jerome K. Jerome',
    publish: '1 Jan, 1889',
    format: '165 - 312 pages',
    language: 'English',
    imageUrl: 'assets/Novels/Three Men In A Boat/Three_Men_In_A_Boat.jpeg',
    pdfUrl: 'assets/Novels/Three Men In A Boat/Three Men In A Boat.pdf',
  },
  {
    id: 'Novel5',
    title: 'Story Of My Life',
    author: 'Helen Keller',
    publish: '1903',
    format: '240 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/Story Of My Life/Story_Of_My_Life.jpeg',
    pdfUrl: 'assets/Novels/Story Of My Life/Story Of My Life.pdf',
  },
  // {
  //   id : "Novel6",
  //   title: "Fifty Shades Of Grey",
  //   author: "E.L.James",
  //   publish: "25 May, 2011",
  //   format: "514 pages, Paperback",
  //   language: "English",
  //   imageUrl: "assets/Novels/Fifty Shades Of Grey/Fifty Shades Of Grey.png",
  //   pdfUrl: "assets/Novels/Fifty Shades Of Grey/Fifty Shades Of Grey.pdf"
  // },
  {
    id: 'Novel7',
    title: 'Crime And Punishment',
    author: 'Fyodor Dostoevsky',
    publish: '1 Jan, 1866',
    format: '671 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/Crime And Punishment/Crime_And_Punishment.png',
    pdfUrl:
      'assets/Novels/Crime And Punishment/Crime_and_Punishment-Fyodor_Dostoevsky.pdf',
  },
  // {
  //   id : "Novel8",
  //   title: "Mind F*ck",
  //   author: "S.T.Abby",
  //   publish: "7 Jul, 2022",
  //   format: "692 pages, Paperback",
  //   language: "English",
  //   imageUrl: "assets/Novels/Mind Fuck/Mind_Fuck.png",
  //   pdfUrl: "assets/Novels/Mind Fuck/Mind Fuck.pdf"
  // },
  {
    id: 'Novel9',
    title: "Man's Search For Meaning",
    author: 'Viktor E. Frankl',
    publish: '1 Jan, 1959',
    format: '165 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/Man_s Search For Meaning/Man_s Search For Meaning.png',
    pdfUrl: 'assets/Novels/Man_s Search For Meaning/Man_s Search For Meaning.pdf',
  },
  {
    id: 'Novel10',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    publish: '1 Jan, 2018',
    format: '336 pages, Hardcover',
    language: 'English',
    imageUrl: 'assets/Novels/The Silent Patient/The Silent Patient.png',
    pdfUrl: 'assets/Novels/The Silent Patient/The Silent Patient.pdf',
  },
  {
    id: 'Novel11',
    title: 'White Nights',
    author: 'Fyodor Dostoevsky',
    publish: '1 Jan, 1848',
    format: '82 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/White Nights/White_Nights.jpeg',
    pdfUrl: 'assets/Novels/White Nights/White_Nights_fiodor_dostoievski.pdf',
  },
  {
    id: 'Novel12',
    title: 'Pride And Prejudice',
    author: 'Jane Austen',
    publish: '28 Jan, 1813',
    format: '479 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/Pride And Prejudice/Pride And Prejudice.png',
    pdfUrl: 'assets/Novels/Pride And Prejudice/Pride And Prejudice.pdf',
  },
  {
    id: 'Novel13',
    title: 'The Metamorphosis',
    author: 'Franz Kafka',
    publish: '1 Oct, 1915',
    format: '77 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/The Metamorphosis/The Metamorphosis.png',
    pdfUrl: 'assets/Novels/The Metamorphosis/The Metamorphosis.pdf',
  },
];

export const sample_books: Book[] = [
  // Music
  // {
  //   id:'1',
  //   title: 'Suzume',
  //   author: 'Tatsuya Endo',
  //   publish: "June  25, 2019",
  //   language: 'English',
  //   favorite: false,
  //   origin: 'Japan',
  //   imageUrl: 'assets/Manga/Spy x Family/Spy x Family.jpg',
  //   pdfUrl: 'assets/Manga/Spy x Family/Spy x Family.pdf',
  //   tags: ['Comedy', 'Action', 'Adventure'],

  //   status: '',format : '',subject: '',
  // },
  // {
  //   id:'2',
  //   title: 'Your Name',
  //   author: 'Makoto Shinkai',
  //   publish: "August 26, 2016",
  //   language: 'English',
  //   origin: 'Japan',
  //   imageUrl: 'assets/Manga/Your Name/Your Name.jpg',
  //   pdfUrl: 'assets/Manga/Your Name/Your Name.pdf',

  //   status: '',format : '',subject: '',
  // },

  // Novels

  {
    id: 'Novel1',
    title: "Gulliver's Travels",
    author: 'Jonathan Swift',
    publish: '1726',
    format: '383 pages',
    language: 'English',
    imageUrl: "assets/Novels/Gulliver's Travels/Gullivers_Travels.jpeg",
    pdfUrl: "assets/Novels/Gulliver's Travels/Gullivers Travels.pdf",

    status: 'N.A.',
    subject: 'N.A.',
    origin: 'N.A.',
  },
  {
    id: 'novel2',
    title: 'A Little Life',
    author: 'Hanya Yanagihara',
    publish: '10 Mar, 2015',
    format: '720 pages',
    language: 'English',
    imageUrl: 'assets/Novels/A Little Life/A_Little_Life.jpeg',
    pdfUrl: 'assets/Novels/A Little Life/A Little Life.pdf',

    status: 'N.A.',
    subject: 'N.A.',
    origin: 'N.A.',
  },
  {
    id: 'Novel3',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    publish: '1 Jan, 1818',
    format: '276 pages',
    language: 'English',
    imageUrl: 'assets/Novels/Frankenstein/Frankenstein.png',
    pdfUrl: 'assets/Novels/Frankenstein/Frankenstein.pdf',

    status: 'N.A.',
    subject: 'N.A.',
    origin: 'N.A.',
  },
  {
    id: 'Novel4',
    title: 'Three Men In A Boat',
    author: 'Jerome K. Jerome',
    publish: '1 Jan, 1889',
    format: '165 - 312 pages',
    language: 'English',
    imageUrl: 'assets/Novels/Three Men In A Boat/Three_Men_In_A_Boat.jpeg',
    pdfUrl: 'assets/Novels/Three Men In A Boat/Three Men In A Boat.pdf',

    status: 'N.A.',
    subject: 'N.A.',
    origin: 'N.A.',
  },
  {
    id: 'Novel5',
    title: 'Story Of My Life',
    author: 'Helen Keller',
    publish: '1903',
    format: '240 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/Story Of My Life/Story_Of_My_Life.jpeg',
    pdfUrl: 'assets/Novels/Story Of My Life/Story Of My Life.pdf',

    status: 'N.A.',
    subject: 'N.A.',
    origin: 'N.A.',
  },
  // {
  //   id : "Novel6",
  //   title: "Fifty Shades Of Grey",
  //   author: "E.L.James",
  //   publish: "25 May, 2011",
  //   format: "514 pages, Paperback",
  //   language: "English",
  //   imageUrl: "assets/Novels/Fifty Shades Of Grey/Fifty Shades Of Grey.png",
  //   pdfUrl: "assets/Novels/Fifty Shades Of Grey/Fifty Shades Of Grey.pdf",

  //   status:"N.A.", subject:"N.A.", origin:"N.A."
  // },
  {
    id: 'Novel7',
    title: 'Crime And Punishment',
    author: 'Fyodor Dostoevsky',
    publish: '1 Jan, 1866',
    format: '671 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/Crime And Punishment/Crime_And_Punishment.png',
    pdfUrl: 'assets/Novels/Crime And Punishment/Crime_and_Punishment-Fyodor_Dostoevsky.pdf',

    status: 'N.A.',
    subject: 'N.A.',
    origin: 'N.A.',
  },
  // {
  //   id : "Novel8",
  //   title: "Mind F*ck",
  //   author: "S.T.Abby",
  //   publish: "7 Jul, 2022",
  //   format: "692 pages, Paperback",
  //   language: "English",
  //   imageUrl: "assets/Novels/Mind Fuck/Mind_Fuck.png",
  //   pdfUrl: "assets/Novels/Mind Fuck/Mind Fuck.pdf",

  //   status:"N.A.", subject:"N.A.", origin:"N.A."
  // },
  {
    id: 'Novel9',
    title: "Man's Search For Meaning",
    author: 'Viktor E. Frankl',
    publish: '1 Jan, 1959',
    format: '165 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/Man_s Search For Meaning/Man_s Search For Meaning.png',
    pdfUrl: 'assets/Novels/Man_s Search For Meaning/Man_s Search For Meaning.pdf',

    status: 'N.A.',
    subject: 'N.A.',
    origin: 'N.A.',
  },
  {
    id: 'Novel10',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    publish: '1 Jan, 2018',
    format: '336 pages, Hardcover',
    language: 'English',
    imageUrl: 'assets/Novels/The Silent Patient/The Silent Patient.png',
    pdfUrl: 'assets/Novels/The Silent Patient/The Silent Patient.pdf',

    status: 'N.A.',
    subject: 'N.A.',
    origin: 'N.A.',
  },
  {
    id: 'Novel11',
    title: 'White Nights',
    author: 'Fyodor Dostoevsky',
    publish: '1 Jan, 1848',
    format: '82 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/White Nights/White_Nights.jpeg',
    pdfUrl: 'assets/Novels/White Nights/White_Nights_fiodor_dostoievski.pdf',

    status: 'N.A.',
    subject: 'N.A.',
    origin: 'N.A.',
  },
  {
    id: 'Novel12',
    title: 'Pride And Prejudice',
    author: 'Jane Austen',
    publish: '28 Jan, 1813',
    format: '479 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/Pride And Prejudice/Pride And Prejudice.png',
    pdfUrl: 'assets/Novels/Pride And Prejudice/Pride And Prejudice.pdf',

    status: 'N.A.',
    subject: 'N.A.',
    origin: 'N.A.',
  },
  {
    id: 'Novel13',
    title: 'The Metamorphosis',
    author: 'Franz Kafka',
    publish: '1 Oct, 1915',
    format: '77 pages, Paperback',
    language: 'English',
    imageUrl: 'assets/Novels/The Metamorphosis/The Metamorphosis.png',
    pdfUrl: 'assets/Novels/The Metamorphosis/The Metamorphosis.pdf',

    status: 'N.A.',
    subject: 'N.A.',
    origin: 'N.A.',
  },

  // Manga

  {
    id: 'Manga1',
    title: 'Spy x Family',
    author: 'Tatsuya Endo',
    status: 'Ongoing',
    publish: 'June 25, 2019',
    language: 'English',
    imageUrl: 'assets/Manga/Spy x Family/Spy x Family.jpg',
    pdfUrl: 'assets/Manga/Spy x Family/Spy x Family.pdf',
    origin: 'Japan',

    format: '',
    subject: 'N.A.',
  },
  {
    id: 'Manga2',
    title: 'Your Name',
    author: 'Makoto Shinkai',
    status: 'Released',
    publish: 'August 26, 2016',
    language: 'English',
    imageUrl: 'assets/Manga/Your Name/Your Name.jpg',
    pdfUrl: 'assets/Manga/Your Name/Your Name.pdf',
    origin: 'Japan',

    format: '',
    subject: 'N.A.',
  },
  {
    id: 'Manga3',
    title: 'Death Note Special',
    author: 'Tsugumi Ohba',
    status: 'Released',
    publish: 'February 3rd, 2020',
    language: 'English',
    imageUrl: 'assets/Manga/Death Note/Death Note Special.png',
    pdfUrl: 'assets/Manga/Death Note/Death Note Special.pdf',
    origin: 'Japan',

    format: '',
    subject: 'N.A.',
  },
  {
    id: 'Manga4',
    title: 'One Piece',
    author: 'Eiichiro Oda',
    status: 'Ongoing',
    publish: 'July 22, 1997',
    language: 'English',
    imageUrl: 'assets/Manga/One Piece/One Piece.png',
    pdfUrl: 'assets/Manga/One Piece/One Piece.pdf',
    origin: 'Japan',

    format: '',
    subject: 'N.A.',
  },
  {
    id: 'Manga5',
    title: 'Blue Lock',
    author: 'Muneyuki Kaneshiro',
    status: 'Released',
    publish: 'March 25, 2023',
    language: 'English',
    imageUrl: 'assets/Manga/Blue Lock/Blue Lock.png',
    pdfUrl: 'assets/Manga/Blue Lock/Blue Lock ch1.pdf',
    origin: 'Japan',

    format: '',
    subject: 'N.A.',
  },
  {
    id: 'Manga6',
    title: 'I Got a Cheat Skill',
    author: 'Miku',
    status: 'Released',
    publish: 'September 10, 2010',
    language: 'English',
    imageUrl: 'assets/Manga/I Got a Cheat Skill/I Got a Cheat Skill.png',
    pdfUrl: 'assets/Manga/I Got a Cheat Skill/I Got a Cheat Skill.pdf',
    origin: 'Japan',

    format: '',
    subject: 'N.A.',
  },
  {
    id: 'Manga7',
    title: 'Attack on Titan',
    author: 'Hajime Isayama',
    status: 'Released',
    publish: 'September 9, 2009',
    language: 'English',
    imageUrl: 'assets/Manga/Attack on Titan/Attack on Titan.png',
    pdfUrl: 'assets/Manga/Attack on Titan/Attack on Titan.pdf',
    origin: 'Japan',

    format: '',
    subject: 'N.A.',
  },
  {
    id: 'Manga8',
    title: 'Jujutsu Kaisen',
    author: 'Akutami Gege',
    status: 'Ongoing',
    publish: 'March 5, 2018',
    language: 'English',
    imageUrl: 'assets/Manga/Jujutsu Kaisen/Jujutsu Kaisen.png',
    pdfUrl: 'assets/Manga/Jujutsu Kaisen/Jujutsu Kaisen.pdf',
    origin: 'Japan',

    format: '',
    subject: 'N.A.',
  },
  {
    id: 'Manga9',
    title: 'Erased',
    author: 'Kei Sanbe',
    status: 'Released',
    publish: 'Feb 21, 2017',
    language: 'English',
    imageUrl: 'assets/Manga/Erased/Erased.jpg',
    pdfUrl: 'assets/Manga/Erased/Erased.pdf',
    origin: 'Japan',

    format: '',
    subject: 'N.A.',
  },

  // Tech

  {
    id: 'Tech1',
    title: 'Probability & Statistics for Scientists',
    author: 'Walpole, Myers, Myers, Ye',
    publish: 'Pearson',
    format: '812 pages',
    subject: 'Mathematics',
    imageUrl: 'assets/Other Books/Probability & Statistics for Scientists/Probability & Statistics for Scientists.png',
    pdfUrl: 'assets/Other Books/Probability & Statistics for Scientists/Text Book of Probability and Statistics.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech2',
    title: 'Discrete Mathematics Applications',
    author: 'Kenneth H. Rosen',
    publish: 'McGraw Hills',
    format: '1071 pages',
    subject: 'Mathematics',
    imageUrl: 'assets/Other Books/Discrete Mathematics Applications/Discrete Mathematics Applications.png',
    pdfUrl: 'assets/Other Books/Discrete Mathematics Applications/Discrete Mathematics Applications.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech3',
    title: 'WorkBook of Ananlytical Skills',
    author: 'Hanya Yanagihara',
    publish: 'D.A.S.C. L.P.U.',
    format: '116 pages',
    subject: 'Ananlytical Skills',
    imageUrl: 'assets/Other Books/WorkBook of Ananlytical Skills/WorkBook of Ananlytical Skills.png',
    pdfUrl: 'assets/Other Books/WorkBook of Ananlytical Skills/Workbook-PEA305.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech4',
    title: 'Concepts And Applications Of UNIX',
    author: 'Sumitabha Das',
    publish: 'The McGraw Hills',
    format: '131 pages',
    subject: 'UNIX',
    imageUrl: 'assets/Other Books/Concepts And Applications Of UNIX.pdf/Concepts And Applications Of UNIX.pdf.png',
    pdfUrl: 'assets/Other Books/Concepts And Applications Of UNIX.pdf/Concepts And Applications Of UNIX.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech5',
    title: 'Beginning Linux Programming',
    author: 'Matthew, Stones',
    publish: 'Wiley Publishing',
    format: '819 pages',
    subject: 'Linux Programming',
    imageUrl: 'assets/Other Books/Beginning Linux Programming/Beginning Linux Programming.png',
    pdfUrl: 'assets/Other Books/Beginning Linux Programming/Beginning Linux Programming, 4 Ed.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech6',
    title: 'Let Us C (14th Edition)',
    author: 'Yashwant Kanetkar',
    publish: 'BPB Publications',
    format: '636 pages',
    subject: 'C Programming',
    imageUrl: 'assets/Other Books/Let Us C/Let Us C.png',
    pdfUrl: 'assets/Other Books/Let Us C/let-us-c-14.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech7',
    title: 'The C Programming Language',
    author: 'Kernighan, Ritche',
    publish: 'Hall Software',
    format: '238 pages',
    subject: 'C Programming',
    imageUrl: 'assets/Other Books/The C Programming Language/The C Programming Language.png',
    pdfUrl: 'assets/Other Books/The C Programming Language/C Language.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech8',
    title: 'C++ by Bjarne Stroustrup',
    author: 'Bjarne Stroustrup',
    publish: 'Pearson Education',
    format: '1366 pages',
    subject: 'C++ Programming',
    imageUrl: 'assets/Other Books/C++ by Bjarne Stroustrup/The_C _Programming_Language_4th_Edition_Bjarne_Stroustrup.pdf.png',
    pdfUrl: 'assets/Other Books/C++ by Bjarne Stroustrup/The_C _Programming_Language_4th_Edition_Bjarne_Stroustrup.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech9',
    title: 'Java',
    author: 'Edward D. Alphons',
    publish: 'Edward D. Alphons',
    format: '42 pages',
    subject: 'Java',
    imageUrl: 'assets/Other Books/Java  Edward D. Alphons/Java  Edward D. Alphons.png',
    pdfUrl: 'assets/Other Books/Java  Edward D. Alphons/Java  Edward D. Alphons.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech10',
    title: 'HTML Cheat Sheet',
    author: 'Free Code Camp',
    publish: 'Free Code Camp',
    format: '15 pages',
    subject: 'HTML Cheat Sheet',
    imageUrl: 'assets/Other Books/HTML Cheat Sheet/HTML Cheat Sheet.png',
    pdfUrl: 'assets/Other Books/HTML Cheat Sheet/Html Cheatsheet.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech11',
    title: 'CSS Cheat Sheet',
    author: 'Free Code Camp',
    publish: 'Free Code Camp',
    format: '23 pages',
    subject: 'CSS Cheat Sheet',
    imageUrl: 'assets/Other Books/CSS Cheat Sheet/CSS Cheat Sheet.png',
    pdfUrl: 'assets/Other Books/CSS Cheat Sheet/CSS Cheatsheet.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech12',
    title: 'JS Cheat Sheet',
    author: 'Free Code Camp',
    publish: 'Free Code Camp',
    format: '22 pages',
    subject: 'JS Cheat Sheet',
    imageUrl: 'assets/Other Books/JS Cheat Sheet/Javascript Cheat Sheet.png',
    pdfUrl: 'assets/Other Books/JS Cheat Sheet/Javascript Cheat Sheet.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech13',
    title: 'Data Communications & Networking',
    author: 'Behrouz A. Forouzan',
    publish: 'McGraw Hills',
    format: '1171 pages',
    subject: 'Computer Networking',
    imageUrl: 'assets/Other Books/Data Communications and Networking/Data Communications and Networking.png',
    pdfUrl: 'assets/Other Books/Data Communications and Networking/Data Communications and Networking.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech14',
    title: 'Computer Organisation And Design',
    author: 'P. Pal Chaudhuri',
    publish: 'PHI Learning',
    format: '920 pages',
    subject: 'Computer Organisation',
    imageUrl: 'assets/Other Books/Computer Organisation And Design/Computer Organisation And Design.png',
    pdfUrl: 'assets/Other Books/Computer Organisation And Design/Computer Organisation And Design_by_p_pal_chaudhuri.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech15',
    title: 'Computer System Architecture',
    author: 'Morris Mano',
    publish: 'Prentice Hall',
    format: '524 pages',
    subject: 'Computer Architecture',
    imageUrl: 'assets/Other Books/Computer System Architecture/Computer System Architecture.png',
    pdfUrl: 'assets/Other Books/Computer System Architecture/Computer System Architecture.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech16',
    title: 'Engineering Physics',
    author: 'H.K.Malik, A.K.Singh',
    publish: 'McGraw Hills',
    format: '840 pages',
    subject: 'Physics',
    imageUrl: 'assets/Other Books/Enginnering Physics/Engineering Physics.jpg',
    pdfUrl: 'assets/Other Books/Enginnering Physics/Engineering Physics.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech17',
    title: 'Machine Learning with Python',
    author: 'Ajigt Singh',
    publish: 'Ajit Singh',
    format: '137 pages',
    subject: 'Machine Learning',
    imageUrl: 'assets/Other Books/Machine Learning With Python/Machine Learning With Python.png',
    pdfUrl: 'assets/Other Books/Machine Learning With Python/Machine Learning With Python.pdf',

    status: '',
    language: '',
    origin: 'N.A.',
  },
  {
    id: 'Tech18',
    title: 'Rich Dad Poor Dad',
    author: 'Robert H. Fiyosaki',
    publish: 'Plata Publishing',
    format: '241 pages',
    subject: 'Econimic Midset',
    imageUrl: 'assets/Other Books/Rich Dad Poor Dad/Rich Dad Poor Dad.png',
    pdfUrl: 'assets/Other Books/Rich Dad Poor Dad/Rich Dad Poor Dad.pdf',

    status: 'Released',
    language: '',
    origin: 'N.A.',
  },
];
